- name: Step 1 - Check_Log
  shell: echo "Checking OOM Error in Logs"
  register: check_log_result

- name: Wait before next task
  ansible.builtin.pause:
    seconds: 30
    
- name: Find the latest WebLogic log file
  shell: "ls -1t {{ weblogic_log_path }}/{{ weblogic_log_file }} | head -n 1"
  register: latest_log_file

- name: Search for OutOfMemoryError in latest log file
  shell: "awk -v d=\"$(date '+%b %d, %Y %H:%M:%S')\" '$0 >= d && /OutOfMemoryError/' {{ latest_log_file.stdout }}"
  register: oom_errors
  changed_when: false
  
- name: Save oom_errors to File
  copy:
    content: "{{ oom_errors.stdout }}"
    dest: "/tmp/oom_errors.txt"
    
- name: Save latest_log to File
  copy:
    content: "{{ latest_log_file.stdout }}"
    dest: "/tmp/latest_log_file.txt"

- name: Notify on Chec_log Completion
  debug:
     msg: "Check_Log completed. Proceeding to Notify."

- name: Check OOM Logs completion 
  import_tasks: Check_log_completion.yml

- name: Wait before next task
  ansible.builtin.pause:
                seconds: 10   
