- name: Read oom_errors from File
  slurp:
    src: "/tmp/oom_errors.txt"
  register: oom_errors_file

- name: Use oom_errors Path
  debug:
    msg: "oom_errors Path: {{ oom_errors_file.content | b64decode }}"

- name: Create an incident in ServiceNow
  servicenow.itsm.incident:
    instance:
       host: "{{ servicenow_instance }}"
       username: "{{ servicenow_user }}"
       password: "{{ servicenow_password }}"
    state: new
    short_description: "WebLogic OutOfMemoryError detected"
    description: "OutOfMemoryError found in {{ latest_log_file.stdout }}. Please investigate."
  register: snow_incident
  when: oom_errors_file.content | length > 0

- name: Display ServiceNow Incident Details
  debug:
     msg: "Incident created: {{ snow_incident.record.task_effective_number | default('Unknown') }}"


- name: Store ServiceNow Incident Number
  set_fact:
      incident_number: "{{ snow_incident.record.task_effective_number }}"
  ignore_errors: yes  # Prevents playbook failure if no error is foundignore_errors: yes

- name: Save Incident Number to a File
  copy:
    content: "{{ snow_incident.record.task_effective_number }}"
    dest: "/tmp/incident_number.txt"
