- name: OOM Automation Pipeline
  hosts: server
  gather_facts: no
  become: yes
  vars_files:
    - vars/main.yml 
  tasks:
    - name: Check OOM Logs
      import_tasks: check_log.yml

    - name: Wait before next task
      ansible.builtin.pause:
        seconds: 10   

    - name: Notify Stakeholders
      import_tasks: notify.yml

    - name: Wait before next task
      ansible.builtin.pause:
        seconds: 10
		
		
    - name: Create Incident
      import_tasks: create_incident.yml

    - name: Wait before next task
      ansible.builtin.pause:
        seconds: 10

		
    - name: Capture HeapDump on OOM
      import_tasks: capture_heapdump.yml

    - name: Wait before next task
      ansible.builtin.pause:
        seconds: 10
		
    - name: Restart WebLogic Server
      import_tasks: restart_weblogic.yml
	  
    - name: Wait before next task
      ansible.builtin.pause:
        seconds: 10
		
		
    - name: Check OOM Reoccurrence
      import_tasks: check_oom_reoccurence.yml

    - name: Wait before next task
      ansible.builtin.pause:
        seconds: 10

    - name: Increase Heap Memory
      import_tasks: increase_heap.yml
	  
    - name: Wait before next task
      ansible.builtin.pause:
        seconds: 10


    - name: Close Incident
      import_tasks: close_incident.yml

    - name: Wait before next task
      ansible.builtin.pause:
        seconds: 10
