- name: OOM Automation Pipeline
  hosts: server
  gather_facts: no
  become: yes
  vars_files:
    - vars/main.yml
  tasks:
     - name: Check OOM Logs completion 
       import_tasks: Check_log_completion.yml

    - name: Wait before next task
      ansible.builtin.pause:
        seconds: 10   
