- name: WebLogic OOM Monitoring & Incident Handling
  hosts: server
  become: yes
  vars_files:
    - vars/main.yml
  tasks:
    - name: Call Check_log dynamically
      include_role:
        name: check_log
 
  #roles:
    - check_log
    - notify
    - create_incident
    - capture_heapdump
    - restart_weblogic
    - check_oom_reoccurence
    - notify
    - increase_heap
    - notify
    - create_problem_ticket
    - close_incident
