- name: Wait before next task
  ansible.builtin.pause:
    seconds: 300

- name: sleep for a specified interval
  command: sleep '{{ sleep_interval }}'

- name: Find the latest WebLogic log file
  shell: "ls -1t {{ weblogic_log_path }}/{{ weblogic_log_file }} | head -n 1"
  register: latest_log_file

- name: Search for OutOfMemoryError in latest log file
  shell: awk -v d="$(date '+%b %d, %Y %H:%M:%S')" ' /OutOfMemoryError|BEA-000802|BEA-000337|BEA-000627/ { print d, $0 } ' "{{ latest_log_file.stdout }}"
  register: oom_errors
  ignore_errors: yes

- name: Print OutOfMemoryError logs on screen
  debug:
    msg: "{{ oom_errors.stdout_lines }}"
  when: oom_errors.stdout | length > 0

- name: Set OOM reoccurrence status
  set_fact:
    oom_reoccurred: "{{ oom_errors.stdout | length > 0 and ansible_local.oom_detected is defined and ansible_local.oom_detected == 'true' }}"

- name: Mark OOM occurrence
  set_fact:
    oom_detected: "{{ oom_errors.stdout | length > 0 }}"
    
- name: Save oom_errors to File
  copy:
    content: "{{ oom_errors.stdout }}"
    dest: "/tmp/oom_errors.txt"
    
- name: Save latest_log to File
  copy:
    content: "{{ latest_log_file.stdout }}"
    dest: "/tmp/latest_log_file.txt"
